name: API Tests CI

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
      - develop # Trigger on pushes to the develop branch (if applicable)
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened] # Trigger on PR creation, updates, and reopens

jobs:
  build-and-test:
    name: Build & Run API Tests
    runs-on: ubuntu-latest # Use a fresh Ubuntu runner provided by GitHub Actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Action to set up Java Development Kit
        with:
          java-version: '17' # Specify the Java version (matches your pom.xml)
          distribution: 'temurin' # Use Eclipse Temurin distribution
          cache: 'maven' # Cache Maven dependencies for faster builds

      - name: Run Maven Clean Install
        run: mvn clean install -DskipTests # Build the project, skip tests for initial install

      - name: Run API Tests with Maven Surefire
        run: mvn test # Execute all tests using Maven Surefire plugin. This generates Allure results.

      - name: Upload Allure results (raw data)
        uses: actions/upload-artifact@v4 # Action to upload generated Allure results as an artifact
        if: always() # Always run this step, even if tests fail, to get the results
        with:
          name: allure-results-raw # Name of the artifact
          path: target/allure-results # Path to the Allure raw results directory (as configured in pom.xml)
          retention-days: 5 # How long to keep the artifact