name: API Tests CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
    types: [opened, synchronize, reopened]

  # NEW: Allows manual trigger from GitHub UI with an input for test tags
  workflow_dispatch:
    inputs:
      test_tags:
        description: 'Tags to include (comma-separated, e.g., smoke, sanity, regression). Leave empty for all tests.'
        required: false
        default: '' # Default to empty to run all tests if no tags specified

jobs:
  build-and-test:
    name: Build & Run API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Clean Install
        run: mvn clean install -DskipTests

      - name: Run API Tests with Maven Surefire
        run: |
          TEST_COMMAND="mvn test"
          # Check if the 'test_tags' input was provided from the manual trigger
          if [ -n "${{ github.event.inputs.test_tags }}" ]; then
            TEST_COMMAND="${TEST_COMMAND} -Dgroups=${{ github.event.inputs.test_tags }}"
          fi
          echo "Running tests with command: ${TEST_COMMAND}"
          eval $TEST_COMMAND # Execute the constructed Maven command

      - name: Upload Allure results (raw data)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-raw
          path: target/allure-results
          retention-days: 5